# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170824_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='name',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='write',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
